### ISSUE TITLE
React Native v.0.13.1: Error building DepdendencyGraph 

### ISSUE THREAD

**Issue by sectore** [timfpark/react-native-location#3]
While updating my app to latest React Native `0.13.1` I run into following error:

```bash
Error building DepdendencyGraph:
 Error: Naming collision detected: {project-folder}/node_modules/react-native/node_modules/react-tools/src/renderers/shared/event/eventPlugins/ResponderTouchHistoryStore.js collides with {project-folder}/node_modules/react-native-location/node_modules/react-native/node_modules/react-tools/src/renderers/shared/event/eventPlugins/ResponderTouchHistoryStore.js
    at HasteMap._updateHasteMap ({project-folder}/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:123:13)
    at {project-folder}/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:95:28
    at tryCallOne ({project-folder}/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at {project-folder}/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush ({project-folder}/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```

Removing `react-native` folder in `/node_modules/react-native-location/node_modules/` does fix this error. 

Or could you update the dependency to `react-native-location` to latest RN  `^0.13.1`, please? 

[EDIT] 
Using [peerDependencies](https://nodejs.org/en/blog/npm/peer-dependencies/) might be helpful, too:
```javascript
// package.json
"peerDependencies": {
    "react-native": ">=0.12"
}
```
[/EDIT]

**Comment by sectore** [comment]
Issue has been fixed with #4 . Dependencies of `react-native` are not installed within `/node_modules/react-native-location/node_modules/` anymore. I'm not sure if an upgrade of Node to `v4.2.1` (from `iojs-v3.3.1`) helped me, too. 

Anyway, Issue can be closed, thanks!
